### ISSUE TITLE
'./data/flickr/trainlabel.mat not found

### ISSUE THREAD

**Issue by wpl18589946597** [pectinid16/ISDH-Tensorflow#1]
hello , in tf_record.py file， label_dir = './data/flickr/trainlabel.mat' is not found ,please  uploading the corresponding file

**Comment by pectinid16** [comment]
Hi, I have update the "train.txt" and "trainlabel.mat" files. I hope that will help.

**Comment by pectinid16** [comment]
@wpl18589946597  Hi, I have updated the "train.txt" and "trainlabel.mat" files. I hope that will help.

**Comment by wpl18589946597** [comment]
thanks you!
