### ISSUE TITLE
 flickr-25k 38 semantic tags

### ISSUE THREAD

**Issue by xueleihan** [pectinid16/ISDH-Tensorflow#2]
I have readed your paper,that is Instance Similarity Deep Hashing for Multi-label Image Retrieval,
your paper mentions that the image of flickr belongs to at least one of the 38 semantic labels,  i have 
readed some papers, however , I can't find them ,Can you provide these 38 semantic tags specifically?

**Comment by pectinid16** [comment]
Hi, you can get the annotations of flickr25k from the official public website, which contains 38 semantic labels with 24 common semantic concepts and 14 more stricter labels.

**Comment by xueleihan** [comment]
您好，还是接着上面的问题，我需要知道38个语义标签是什么和他们的顺序,这样我才能对测试集的图片进行标注和测试，麻烦上传一下，非常感谢

**Comment by pectinid16** [comment]
@xueleihan  You can download the annotations of flickr25k from [here](http://press.liacs.nl/mirflickr/mirflickr25k.v2/mirflickr25k_annotations_v080.zip) . Hope this will be help.
